### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by samueldurantes** [Riku32/waifu.pics#1]
I was wondering if there is a problem if I create a library for your API...

**Comment by samueldurantes** [comment]
Here is the library, which I developed for your API https://github.com/tentaclenotsoft/node-waifu.pics

**Comment by Riku32** [comment]
Thanks, the API is currently being updated but ill try to keep legacy compatibility. I recommend you use https://waifu.pics/api/endpoints for the list of endpoints since they might change in the future.

**Comment by samueldurantes** [comment]
Do you have any means of contact?

**Comment by Riku32** [comment]
My discord tag is Riku#1111
